config/routes.rb
Rails.application.routes.draw do
  resources :companies

  devise_for :users

  resources :users do
    get  'lock'
    get  'unlock'
  end

  resources :buys do
    get  'add_customer', on: :member
    post 'create_customer', on: :member
    get  'add_phone', on: :member
    post 'create_buy_details', on: :member
    post 'print_coupon', on: :member
    
  end

  resources :coupons

  resources :buy_details

  resources :customers do

  end

  resources :models

  resources :trademarks do
  
  end

  resources :states
  resources :sucursals
  resources :members
  

  get 'welcome/index'

  root 'welcome#index'

  get   'quote_phones'      => 'sell_phones#quote_phone'
  post  'calculate_price'   => 'sell_phones#calculate_price'
  post  'generate_buy'      => 'sell_phones#generate_buy'
  get   'add_customer'      => 'sell_phones#add_customer'
  get   'finalize_buy/:id'  => 'sell_phones#finalize_buy'
  get   'buy_sucursal'      => 'buys#buy_sucursal'
  get   'buy_all'           => 'buys#buy_all'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login

  devise  :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable
  
  

  has_many :members
  has_many :sucursals, through: :members
  #
  # Associations
  #

  # has_many :project_members

  #
  # Validations
  #

  # validates :username, presence: true
  # validates :username, uniqueness: { case_sensitive: false }

  #
  # Scopes
  #

  scope :locked      , -> { where('users.locked_at IS NOT NULL') }
  scope :enabled     , -> { where('users.locked_at IS NULL') }

  #
  # Callbacks
  #

  # after_create :generate_access_token

  #
  # Class methods
  #

  # def self.find_first_by_auth_conditions(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if login = conditions.delete(:login)
  #     where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
  #   else
  #     where(conditions).first
  #   end
  # end

  #
  # Instance methods
  #

  def full_name
    return username if name.nil? and last_name.nil?
    "#{name.capitalize} #{last_name}"
  end

  def locked?
    (locked_at != nil)
  end

  def generate_access_token
    token = loop do
      random_token = Base64.encode64(SecureRandom.uuid)
      break random_token unless self.class.exists?(access_token: random_token)
    end

    update_column(:access_token, token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_user, only: [:lock, :unlock, :edit, :update, :add_to_project]

  def index
    
    @users = User.all
    
    respond_to do |format|
      format.html do 
        render @user
      end 
      format.json do
        @user = User.where(email: params[:email]).first
        render json: @user 
      end
    end
  end

  def show
    render json: @user
  end
  
  def new
    @user = User.new
    @sucursal_id = params[:sucursal_id]
  end

  def create
    @user = User.new(user_params)
    @sucursal = Sucursal.find(params[:sucursal_id])
    raise @user.inspect

    respond_to do |format|
      format.html do 
        if @user.save
            @sucursal.members.create(user: @user, role: :collaborator)
          flash[:success] = 'Usuario creado exitosamente'
          redirect_to users_path
        else
          flash[:danger] = 'No se pudo crear el usuario'
          render :new
        end
      end 
      format.json do
        if @user.save
           render json: @user 
        end
      end
    end
  end

  def edit
    
  end

  def update
    options = params.key?(:update_password) ? password_params : user_params
    if @user.update_attributes(options)
      flash[:success] = 'Usuario actualizado exitosamente.'
      redirect_to users_path
    else
      flash[:danger] = 'No se pudo actualizar el usuario.'
      render 'edit'
    end
  end

  def lock
    if current_user == @user
      flash[:danger] = 'No puedes bloquear tu cuenta.'
      redirect_to(users_path) and return
    end

    if @user.lock_access!(send_instructions: false)
      flash[:success] = 'Usuario bloqueado exitosamente.'
    else
      flash[:danger] = 'No se pudo bloquear el usuario.'
    end

    redirect_to users_path
  end

  def unlock
    if @user.unlock_access!
      flash[:success] = 'Usuario habilitado exitosamente.'
    else
      flash[:danger] = 'No se pudo habilitar el usuario.'
    end

    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:user_id] || params[:id])
  end

  def user_params
    params.require(:user).permit(
      :username, :name, :last_name, :email,
      :position, :address, :rut,
      :contact_number, :resposible_name,
      :password, :password_confirmation
    )
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(
     :username, :name, :last_name, :email,
      :position, :address, :rut,
      :contact_number, :resposible_name,
      :password, :password_confirmation
    )
  end

end

app/views/users/_form.haml
.col-sm-12
  = form_for @user, html: { class: 'form-horizontal'} do |f|
    .form-group.form-heading
      .col-sm-12{style: 'margin-left: 323px;'}
        %h4 Información general


    .form-group
      = f.label "Nombre", class: 'control-label col-sm-3'
      .col-sm-6
        = f.text_field :username, class: 'form-control', placeholder: 'Ejemplo: Juan'
    .form-group
      = f.label "Rut", class: 'control-label col-sm-3'
      .col-sm-6
        =f.text_field :rut, class: 'form-control', placeholder: 'Ejemplo: 15789345-5'    
   
    .form-group
      = f.label :email, class: 'control-label col-sm-3'
      .col-sm-6
        = f.email_field :email, class: 'form-control', placeholder: 'Ejemplo@ejemplo.com'

    
    .form-group
      = f.label "Dirección", class: 'control-label col-sm-3'
      .col-sm-6
        = f.text_field :address, class: 'form-control', placeholder: 'Ejemplo: Direccion #1234'
        
    .form-group
      = f.label "Teléfono de Contacto", class: 'control-label col-sm-3'
      .col-sm-6
        = f.text_field :contact_number, class: 'form-control', placeholder: 'Ejemplo: +569 94532144'

    - if @user.new_record?
      .form-group
        = f.label 'Contraseña', class: 'control-label col-sm-3'
        .col-sm-3
          = f.password_field :password, class: 'form-control', placeholder: 'Contraseña'
        .col-sm-3
          = f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirme su contraseña'

    .form-group
      .col-sm-6{style: 'margin-left: 321px;'}
        = f.submit 'Guardar', class: 'btn btn-success'
        = link_to 'Cancelar', sucursal_path(@sucursal_id) , class: 'btn btn-default'

app/views/users/edit.haml
%h1.text-center Editar Sucursal
%hr
%br
  / .pull-right
  /   = link_to 'Cancelar', params[:project_id].nil? ? users_path : members_project_path(params[:project_id]), class: 'btn btn-default'
  /   = link_to 'Guardar', nil, class: 'btn btn-success', 'data-submit' => 'user_form'

.separator

.main-content
  = render 'form'
  .clearfix

app/views/users/index.haml
%h1.heading.text-center Lista de sucursales
%hr
%br
    

.content-wrapper
  .sub-menu-wrapper
    / %ul#sub-menu.nav.nav-tabs.navbar-left
    /   %li{ class: "#{'active' if(params[:type].nil?)}" }
    /     = link_to 'Usuarios habilitados', users_path
    /     %span
    /   %li{ class: "#{'active' if(params[:type].to_s == 'locked')}" }
    /     = link_to 'Usuarios bloqueados', users_path(type: 'locked')
    /     %span
    /   %li{ class: "#{'active' if(params[:type].to_s == 'all')}" }
    /     = link_to 'Todos los usuarios', users_path(type: 'all')
    /     %span

    / .pull-right
    /   %form.form-inline.quick-search{:action => ""}
    /     .form-group
    /       %input.form-control{type: 'text', name: 'q', placeholder: 'Buscar', value: params[:q].to_s}
    /       - unless params[:type].blank?
    /         %input{type: 'hidden', name: 'type', value: params[:type].to_s}
    
    .clearfix
    = link_to new_sucursal_path, class: 'btn btn-success' do
      %i.fa.fa-plus
      %span Nueva sucursal
  .main-content
    - if @users.any?
      %table.table.table-hover
        %thead
          %tr
            %th Nombre de sucursal
            %th Correo electrónico
            %th Dirección
            %th Teléfono de Contacto
            %th 
        %tbody 
          - @users.each do |user|
            %tr
              %td
                %span= user.username
              %td
                %span= user.email
              %td
                %span= user.address
              %td
                %span= user.contact_number
              / %td
              /   - if user.sign_in_count > 0
              /     %span= "Hace #{time_ago_in_words(user.last_sign_in_at)}"
              %td{ align: 'right' }
                .btn-group
                  = link_to edit_user_path(user), title: 'Editar', class: 'btn btn-default btn-sm with-tooltip' do
                    %i.fa.fa-pencil

                  / - if user.locked?
                  /   = link_to user_unlock_path(user), title: 'Desbloquear', class: 'btn btn-default btn-sm with-tooltip' do
                  /     %i.fa.fa-unlock
                  / - else
                  /   = link_to user_lock_path(user), title: 'Bloquear', class: 'btn btn-default btn-sm with-tooltip' do
                  /     %i.fa.fa-lock
      
      / .paginator-wrapper= paginate @users
    - else
      .empty-list
        %h4 No se encontraron usuarios

app/views/users/new.haml
%h1.text-center Nuevo Miembro
%hr
%br

  / .pull-right
  /   = link_to 'Cancelar', users_path, class: 'btn btn-default'
  /   = link_to 'Guardar', nil, class: 'btn btn-success', 'data-submit' => 'user_form'

.separator

.main-content
  = render 'form'
  .clearfix