config/routes.rb
Rails.application.routes.draw do
  resources :companies

  devise_for :users

  resources :users do
    get  'lock'
    get  'unlock'
  end

  resources :buys do
    get  'add_customer', on: :member
    post 'create_customer', on: :member
    get  'add_phone', on: :member
    post 'create_buy_details', on: :member
    post 'print_coupon', on: :member
    
  end

  resources :coupons

  resources :buy_details

  resources :customers do

  end

  resources :models

  resources :trademarks do
  
  end

  resources :states
  resources :sucursals
  resources :members
  

  get 'welcome/index'

  root 'welcome#index'

  get   'quote_phones'      => 'sell_phones#quote_phone'
  post  'calculate_price'   => 'sell_phones#calculate_price'
  post  'generate_buy'      => 'sell_phones#generate_buy'
  get   'add_customer'      => 'sell_phones#add_customer'
  get   'finalize_buy/:id'  => 'sell_phones#finalize_buy'
  get   'buy_sucursal'      => 'buys#buy_sucursal'
  get   'buy_all'           => 'buys#buy_all'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/buy.rb
class Buy < ActiveRecord::Base
  enum status: [ :pending, :finished ]

  has_many :buy_details , dependent: :destroy
  has_one :coupon
  
  belongs_to :customer
  belongs_to :member

  accepts_nested_attributes_for :buy_details

  def get_total_price
    total_value = 0
    self.buy_details.each do |d|
      unless d.price.nil?
        total_value += d.price   
      end 
    end
    return total_value
  end

  def self.to_csv(buy_excel)
    #raise buy_excel.inspect
    CSV.generate(col_sep: "\t") do |csv|

      headers = [
        'Marca',
        'Modelo',
        'Estado',
        'Precio',
        'Fecha'
      ]
       total_value=0
      csv << headers

      buy_excel.each do |buy|
        buy.buy_details.each do |detail|
          #raise detail.inspect
            total_value += detail.price 
          csv << [  
              detail.model.trademark.name,
              detail.model.name,
              detail.state.name,
              detail.price,
              detail.created_at.strftime('%d/%m/%Y %H:%M:%S')

          ] 
        end
      end
      csv << []
      csv << ['','','Total', total_value]
    end
  end
end

app/models/buy_detail.rb
class BuyDetail < ActiveRecord::Base
  belongs_to :buy
  belongs_to :state
  belongs_to :model

  validates :model, :state, presence: true

  before_save :calculate_price!

  def calculate_price
    (model.price * state.factor) / 100
  end

  def self.to_csv(options = {})
    CSV.generate(col_sep: "\t") do |csv|
    #raise self.buy_details.inspect

      headers = [
        'Marca',
        'Modelo',
        'Estado',
        'Precio',
        'Fecha'
      ]

      csv << headers

      all.each do |detail|
        csv << [
          detail.model.trademark.name,
          detail.model.name,
          detail.state.name,
          detail.price,
          detail.created_at.strftime('%d/%m/%Y %H:%M:%S')
        ]
      end
    end
  end

  private

  def calculate_price!
    self.price = calculate_price
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :sucursals, dependent: :destroy

  validates :name, presence: true
  validates :contact_phone, presence: true
  validates :contact_phone, length: { is: 8 }
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  enum status: [:pending , :printed] 
  belongs_to :buy

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :buys
  validates :rut, presence: true
  validates :rut, format: {:with => /\A(\d{1,3})(\d{1,3})(\d{1,3})\-(k|\d{1})\Z/i, message: "el rut %{value} ingresado no es valido."}
  validates :name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => Devise.email_regexp
  validates :phone, presence: true
  validates :phone, length: { is: 8 }


  def full_name
    # primer_apellido = last_name.split(' ').first
    # segundo_apellido = last_name.split(' ').last
    # "#{name.capitalize} #{primer_apellido.capitalize} #{segundo_apellido.capitalize}"
    "#{name.capitalize} #{last_name}"
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
  enum role: [ :collaborator, :admin ]

  belongs_to :sucursal
  belongs_to :user, dependent: :destroy

  delegate :full_name, :name, to: :user
  has_many :buys
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :trademark
  has_many :buy_details

  validates :name, presence: true
  validates :price, presence: true

  #
  #Methods
  #

end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :buy_details
  validates :factor, numericality: true

end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  belongs_to :company
  
  has_many  :members, dependent: :destroy
  has_many  :users, through: :members, source: :user
end

app/models/trademark.rb
class Trademark < ActiveRecord::Base
  has_many :models, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login

  devise  :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable
  
  

  has_many :members
  has_many :sucursals, through: :members
  #
  # Associations
  #

  # has_many :project_members

  #
  # Validations
  #

  # validates :username, presence: true
  # validates :username, uniqueness: { case_sensitive: false }

  #
  # Scopes
  #

  scope :locked      , -> { where('users.locked_at IS NOT NULL') }
  scope :enabled     , -> { where('users.locked_at IS NULL') }

  #
  # Callbacks
  #

  # after_create :generate_access_token

  #
  # Class methods
  #

  # def self.find_first_by_auth_conditions(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if login = conditions.delete(:login)
  #     where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
  #   else
  #     where(conditions).first
  #   end
  # end

  #
  # Instance methods
  #

  def full_name
    return username if name.nil? and last_name.nil?
    "#{name.capitalize} #{last_name}"
  end

  def locked?
    (locked_at != nil)
  end

  def generate_access_token
    token = loop do
      random_token = Base64.encode64(SecureRandom.uuid)
      break random_token unless self.class.exists?(access_token: random_token)
    end

    update_column(:access_token, token)
  end
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    html = ""

    unless @user.blank?
      @user.errors.full_messages.each do |e|
        html += "#{e}<br/>"
      end
    end
  html.html_safe
  end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/shared/_main_nav.haml
%nav.navbar.navigation-navbar
  .navbar-header.text-center
    %a.navbar-brand{ href: root_path }
      %img{src: asset_url('logo.png'), alt: '', width: 180}

    %button.navbar-toggle.collapsed{ type: 'button', 'data-toggle' => 'collapse', 'data-target' => '.bs-navbar-collapse' }
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar

  .collapse.navbar-collapse.bs-navbar-collapse
    %ul.nav.navbar-nav.main-menu
      %li
        = link_to root_path do
          %span Inicio
      %li{ class: "#{'active' if params[:controller] == 'buys' || !@buy.nil? }" }
        = link_to new_buy_path do
          / .fa.fa-mobile-phone
          %span Comprar Teléfono

      %li.dropdown
        = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do
          %span Mantenedores
          %span.caret
        %ul.dropdown-menu-right.dropdown-menu{ role: "menu", style: 'background-color:#2d9b36;' }
          %li= link_to " Teléfonos",trademarks_path, class: 'fa fa-phone'
          %li= link_to " Estados", states_path, class: 'fa fa-tags'
          %li= link_to " Clientes", customers_path, class: 'fa fa-group'
          %li= link_to " Compañias", companies_path, class: 'fa fa-building'
      %li.dropdown
        = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do
          %span Reportes
          %span.caret
        %ul.dropdown-menu-rigth.dropdown-menu{ role: "menu", style: 'background-color:#2d9b36'}
          %li= link_to "Por Sucursales", buy_sucursal_path, class: 'fa fa-line-chart'
          %li= link_to "Todas las compras", buy_all_path, class: 'fa fa-line-chart'   
     
    %ul.nav.navbar-nav.main-menu.pull-right  
      %li.dropdown
        = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do
          %span= current_user.username
          %span.caret
        %ul.dropdown-menu-right.dropdown-menu{ role: "menu", style: 'background-color:#2d9b36;' }
          / %li= link_to 'Mi cuenta'
          %li= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete

- if alert_message?
  .main-notificator
    .alert.alert-dismissible{ class: alert_type }
      %button.close{ 'data-dismiss' => 'alert' } &times;
      %p.text-center= alert_content