config/routes.rb
Rails.application.routes.draw do
  resources :companies

  devise_for :users

  resources :users do
    get  'lock'
    get  'unlock'
  end

  resources :buys do
    get  'add_customer', on: :member
    post 'create_customer', on: :member
    get  'add_phone', on: :member
    post 'create_buy_details', on: :member
    post 'print_coupon', on: :member
    
  end

  resources :coupons

  resources :buy_details

  resources :customers do

  end

  resources :models

  resources :trademarks do
  
  end

  resources :states
  resources :sucursals
  resources :members
  

  get 'welcome/index'

  root 'welcome#index'

  get   'quote_phones'      => 'sell_phones#quote_phone'
  post  'calculate_price'   => 'sell_phones#calculate_price'
  post  'generate_buy'      => 'sell_phones#generate_buy'
  get   'add_customer'      => 'sell_phones#add_customer'
  get   'finalize_buy/:id'  => 'sell_phones#finalize_buy'
  get   'buy_sucursal'      => 'buys#buy_sucursal'
  get   'buy_all'           => 'buys#buy_all'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :sucursals, dependent: :destroy

  validates :name, presence: true
  validates :contact_phone, presence: true
  validates :contact_phone, length: { is: 8 }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @sucursals = @company.sucursals.order(name: :asc)
  end

  # GET /companies/new
  def new
    @company = Company.new
    @option = 'Guardar'
  end

  # GET /companies/1/edit
  def edit
    @option = 'Editar'
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "La compañia #{@company.name} se ha creado exitosamente."
      redirect_to companies_path
    else
      if @company.name.empty?
        flash[:danger] = "Debe ingresar un nombre de compañia."
      elsif @company.contact_phone.empty?
        flash[:danger] = "Debe ingresar un numero de contacto."
      elsif @company.contact_phone.length != 8
        flash[:danger] = "Debe ingresar 8 digitos, Ej: 68399419."
      else
        flash[:danger] = "Hubo un problema para crear una compañia."
      end
      render :new
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    if @company.update(company_params)
      flash[:success] = "La compañia #{@company.name} se ha editado exitosamente."
      redirect_to companies_path
    else
      if @company.name.empty?
        flash[:danger] = "Debe ingresar un nombre de compañia."
      elsif @company.contact_phone.empty?
        flash[:danger] = "Debe ingresar un numero de contacto."
      elsif @company.contact_phone.length != 8
        flash[:danger] = "Debe ingresar 8 digitos, Ej: 68399419."
      else
        flash[:danger] = "Hubo un problema para crear una compañia."
      end
      render :edit
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @nombre = @company.name
    if @company.destroy
      flash[:success] = "Se ha eliminado la compañia #{@nombre} exitosamente."
    else
      flash[:danger] = "Hubo problemas para eliminar la compañia #{@nombre}"
    end
    redirect_to companies_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description, :contact_phone)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.haml
= form_for @company, html: { class: 'form-horizontal', role: 'form'}  do |f| 
  .form-group.name_field
    = f.text_field :name , class: 'form-control company_name' ,placeholder: 'Ingrese una nombre'
    .company_name-empty.hidden.text-danger
      Debe ingresar un nombre
  .form-group.phone_field
    = f.text_field :contact_phone , class: 'form-control company_phone' ,placeholder: 'Ingrese una Teléfono'
    .company_phone-empty.hidden.text-danger
      Debe ingresar un teléfono de contacto
    .company_phone-enough.hidden.text-danger
      Debe ingresar 8 digitos, Ej: 68399419
  .form-group
    = f.text_area :description , class: 'form-control company_description' ,placeholder: 'Ingrese una descripción'
    .company_description-empty.hidden.text-danger
      Debe ingresar una descripción
  .form-group
    = f.submit "#{@option} compañia", class: 'btn btn-success', id: "buton-company"
    = link_to ' Cancelar', companies_path, class: 'btn btn-default' 

app/views/companies/edit.haml
%h1.text-center Editar Compañia
%hr
%br
.row
  .col-sm-12
    .col-sm-3
    .form-body.col-sm-5{ style: 'margin-left:50px;' }
      = render 'form'

    
        
        

app/views/companies/index.haml
%h1.text-center Lista de Compañias
%hr
%br
.row
  .col-md-3
  .col-md-5
    - unless @companies.empty?
      .option-button
        = link_to ' Agregar Compañia', new_company_path, class: 'btn btn-success'
      %br
      .company-index
      %table.table.table-striped
        %thead
        %tbody
          - @companies.each do |companies|
            %tr
              %td
                %strong
                  = companies.name
              %td
                = link_to " Ver Sucursales ", companies, class: 'btn btn-default fa fa-eye'
              %td
                = link_to " Editar", edit_company_path(companies), class: 'btn btn-default fa fa-edit'
              %td
                = link_to " Eliminar", companies, method: :delete, data: { confirm: "¿Estás Seguro que deseas eliminar la compañia #{companies.name}?"}, class: 'btn btn-danger fa fa-trash'
    - else
      .empty-companies.text-center
      %h4
        %center
          No existen modelos para la marca 
          %br
          %br
          = link_to ' Agregar Compañia', new_company_path, class: 'btn btn-lg btn-success'

app/views/companies/new.haml
%h1.text-center Agregar una compañia
%hr
%br
.row
  .col-sm-12
    .col-sm-3
    .form-body.col-sm-5{ style: 'margin-left:50px;' }
      = render 'form'
        

app/views/companies/show.haml
%h1
  .title.text-center
    Compañia
    = @company.name.capitalize
%hr
%br
.row
  .col-sm-12
    .col-sm-1
    - if !@sucursals.empty?
      .index-sucursals.col-sm-10
        .option-button
          = link_to ' Agregar Sucursal', new_sucursal_path(company_id: @sucursals.first.company_id), class: 'btn btn-success'
          = link_to ' Ver Compañia', companies_path, class: 'btn btn-default'
        %br
        .sucursals-index
        %table.table.table-striped
          %thead
            %tr
              %th Nombre
              %th Dirección
              %th Nombre contacto
              %th Numero contacto
              %th Email de sucursal 
              %th{:colspan => 2}
          %tbody
            - @sucursals.each do |sucursals|
              %tr
                %td
                  %strong
                    = sucursals.name
                %td
                  = "#{sucursals.address}"
                %td
                  = sucursals.responsible_name
                %td
                  = sucursals.contact_number
                %td
                  = sucursals.email  
                %td
                  = link_to " Ver sucursal", sucursals, class: 'btn btn-default fa fa-eye'
                  = link_to " Editar", edit_sucursal_path(sucursals), class: 'btn btn-default fa fa-edit'
                  = link_to " Eliminar", sucursals, method: :delete, data: { confirm: "¿Estás Seguro que deseas eliminar el modelo #{sucursals.name}?"}, class: 'btn btn-danger fa fa-trash'
    - else
      .empty-models.text-center
        %h4
          No existen Sucursales para la Compañia.
          = "#{@company.name}"
        %br
        = link_to ' Agregar Sucursales', new_sucursal_path(company_id: @company.id), class: 'btn btn-lg btn-success ' 
        = link_to ' Ver Compañias', companies_path, class: 'btn btn-lg btn-default'


      