config/routes.rb
Rails.application.routes.draw do
  resources :companies

  devise_for :users

  resources :users do
    get  'lock'
    get  'unlock'
  end

  resources :buys do
    get  'add_customer', on: :member
    post 'create_customer', on: :member
    get  'add_phone', on: :member
    post 'create_buy_details', on: :member
    post 'print_coupon', on: :member
    
  end

  resources :coupons

  resources :buy_details

  resources :customers do

  end

  resources :models

  resources :trademarks do
  
  end

  resources :states
  resources :sucursals
  resources :members
  

  get 'welcome/index'

  root 'welcome#index'

  get   'quote_phones'      => 'sell_phones#quote_phone'
  post  'calculate_price'   => 'sell_phones#calculate_price'
  post  'generate_buy'      => 'sell_phones#generate_buy'
  get   'add_customer'      => 'sell_phones#add_customer'
  get   'finalize_buy/:id'  => 'sell_phones#finalize_buy'
  get   'buy_sucursal'      => 'buys#buy_sucursal'
  get   'buy_all'           => 'buys#buy_all'

end

app/models/buy.rb
class Buy < ActiveRecord::Base
  enum status: [ :pending, :finished ]

  has_many :buy_details , dependent: :destroy
  has_one :coupon
  
  belongs_to :customer
  belongs_to :member

  accepts_nested_attributes_for :buy_details

  def get_total_price
    total_value = 0
    self.buy_details.each do |d|
      unless d.price.nil?
        total_value += d.price   
      end 
    end
    return total_value
  end

  def self.to_csv(buy_excel)
    #raise buy_excel.inspect
    CSV.generate(col_sep: "\t") do |csv|

      headers = [
        'Marca',
        'Modelo',
        'Estado',
        'Precio',
        'Fecha'
      ]
       total_value=0
      csv << headers

      buy_excel.each do |buy|
        buy.buy_details.each do |detail|
          #raise detail.inspect
            total_value += detail.price 
          csv << [  
              detail.model.trademark.name,
              detail.model.name,
              detail.state.name,
              detail.price,
              detail.created_at.strftime('%d/%m/%Y %H:%M:%S')

          ] 
        end
      end
      csv << []
      csv << ['','','Total', total_value]
    end
  end
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy, :add_customer, :create_customer, :add_phone, :print_coupon]

  require 'barby'
  require 'barby/barcode/ean_13'
  require 'barby/outputter/html_outputter'
  
  def print_coupon
    if @buy.coupon.update(status: :printed)
      flash[:success] = "El cupón de descuento se ha impreso exitosamente."
    else
      flash[:danger] = "Hubo un problema el imprimir el cupón de descuento."
    end
    redirect_to @buy
  end
  
  def add_phone
    @buy_detail = @buy.buy_details.new
    @trademarks = Trademark.all
    @states     = State.all
    @models     = Model.where("trademark_id = ?", Trademark.first.id)      
  end


  def add_customer
    @customer = Customer.new
  end

  def create_customer
    @customer = Customer.new(customer_params)

    if RUT.validar(customer_params[:rut]) 
      if @customer.save
        @buy.customer_id = @customer.id
        if @buy.save
          flash[:success] = "Excelente!! antes de finalizar la compra, quizas el cliente desea agregar otro teléfono."
          redirect_to @buy
        else
          flash[:danger] = "Hubo un problema al asignar el cliente con la compra realizada."
          redirect_to add_customer_buy_path(@buy.id)
        end
      else
        flash[:danger] = "Debe ingresar todos los datos que se solicitan."
        redirect_to add_customer_buy_path(@buy.id)
      end
    else
  #end unless 
      flash[:danger]= "El rut #{customer_params[:rut]} no es valido"
      redirect_to add_customer_buy_path(@buy.id)
    end
    
  end


  def index
    @buys = Buy.where(status: 1)
  end

  def show
    unless @buy.coupon.nil?
      @barcode = Barby::EAN13.new(@buy.coupon.barcode)
      @barcode_for_html = Barby::HtmlOutputter.new(@barcode)  
    end
    
  end

 
  def new
    @buy        = Buy.new
    @buy.buy_details.new
    
    @trademarks = Trademark.all
    @states     = State.all
    @models     = Model.where("trademark_id = ?", Trademark.first.id)      
  end


  def buy_sucursal
    #raise params[:q].inspect
     @search = Buy.search(member_sucursal_name_cont: params[:q])
     @buys = @search.result.includes(:buy_details).includes(:member).where(status: 1).page(params[:page]).per(10)
     @buy_excel = @search.result.includes(:buy_details).includes(:member).where(status: 1)
      #raise params[:buy].inspect
     respond_to do |format|
     
      format.html
      format.xls { send_data Buy.to_csv(@buy_excel)}
     end
  end
  
  def buy_all
    @buys = Buy.includes(:buy_details).where(status: 1).page(params[:page]).per(10)
    #raise @buy.inspect

    @buy_details = BuyDetail.joins(:buy).where('buys.status = 1')

    respond_to do |format|
      format.html
      #format.csv { send_data @buys.to_csv }
      format.xls { send_data @buy_details.to_csv }
    end    
  end

  def create
    @buy = Buy.new(buy_params)
    
    @buy.member = current_user.members.first


    respond_to do |format|
      if @buy.save
        flash[:success] = "Bien hecho!! ahora ingrese los datos del cliente."
        format.html { redirect_to add_customer_buy_path(@buy.id)}
        format.json { render :show, status: :created, location: @buy }
      else
        flash[:danger] = "Debe ingresar toda la información para continuar."
        format.html { redirect_to new_buy_path}
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
    
  end


  def update
    respond_to do |format|
      if @buy.update(buy_params)
        flash[:success] = "Bien hecho!! Has ingresado otro teléfono."
        #{@buy_detail.model_id} #{@buy_detail.model.name}.
        format.html { redirect_to @buy}
        format.json { render :show, status: :ok, location: @buy }
      else
        flash[:danger] = "Debe ingresar toda la información para continuar."
        format.html { redirect_to add_phone_buy_path(@buy)}
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @buy.destroy
      flash[:success] = "Se ha cancelado la compra exitosamente."
    else
      flash[:danger] = "Hubo problemas para cancelar la compra."
    end
    redirect_to root_path
  end

  private
   
    def set_buy
      @buy = Buy.find(params[:id])
    end

    def buy_params
      params.require(:buy).permit(
        buy_details_attributes: [:model_id, :state_id,:price]
      )
    end

    def customer_params
      params.require(:customer).permit(:name, :last_name, :rut, :email, :address, :phone)
    end
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/buys/_buy_modals.haml
- unless @buy.coupon.nil?
  .modal#show-coupon
    .modal-dialog
      .modal-content
        .modal-header
          %button{ type: "button", class: "close", 'data-dismiss' => "modal" } &times;
          %h4.modal-title.text-center 
            Fecha de generación de cupón:
            = @buy.coupon.created_at.strftime('%d/%m/%Y') 
        .modal-body{style: 'margin-bottom: 20px;'}
          .form-group
            .row
              .col-md-1
              .col-md-10
                %br
                .show-group-index
                  %table.table.table-striped
                    %tbody
                      %tr
                        %td
                          Fecha de vencimiento:
                        %td
                          = @buy.coupon.end_date.strftime('%d/%m/%Y') 
                          %br
                          = @buy.coupon.end_date.strftime('%H:%m') 
                          hrs
                      %tr
                        %td
                          Cliente:
                        %td
                          = @buy.customer.rut
                          %br
                          = @buy.customer.full_name
                      %tr
                        %td
                          Sucursal:
                        %td
                          = @buy.member.sucursal.name

                      %tr
                        %td
                          Valor Cupón:
                        %td
                          = number_to_currency(@buy.coupon.price, precision: 0, separator: ",", delimiter: ".") 
                  .barcode{style: 'margin-left:90px;'}       
                    = raw @barcode_for_html.to_html
                    %br
                    = @buy.coupon.barcode_read

        .modal-footer
          .pull-right
            = link_to 'Imprimir cupón', print_coupon_buy_path(@buy), method: :post ,class: 'btn btn-primary', data: { dismiss: 'modal' } 
            = link_to 'Cancelar', '#', class: 'btn btn-link', data: { dismiss: 'modal' }
            

app/views/buys/_customer_form.haml
.row
  .col-sm-12
    .col-sm-3
    .form-body-customer.col-sm-4
      = form_for @customer, url: create_customer_buy_path(@buy), html: { class: 'form-inline', role: 'form'}  do |f|

        .form-group.rut{style: 'margin-bottom:20px; margin-left:12px;'}
          = f.text_field :rut, class: 'form-control col-sm-6',placeholder: 'Ingrese rut, Ej: 16468949-2', style: 'width:350px'
          .rut-invalid.hidden.text-danger
            El rut es incorrecto.
          .format-rut-invalid.hidden.text-danger
            El formato del rut es incorrecto,  Ej: 16468949-2.
        .form-group.name{style: 'margin-bottom:20px;margin-left:13px;'}
          = f.text_field :name, class: 'form-control', placeholder: 'Ingrese nombre, Ej: Pedro', style: 'width:350px'
          .name-empty.hidden.text-danger
            Ingrese Nombre, Ej: Pedro.
        .form-group.last_name{style: 'margin-bottom:20px;margin-left:13px;'}
          = f.text_field :last_name, class: 'form-control', placeholder: 'Ingrese Apellidos, Ej: Carrizo Montoya.', style: 'width:350px'
          .last_name-empty.hidden.text-danger
            Ingrese Apellidos, Ej: Carrizo Montoya.

        .form-group.email{style: 'margin-bottom:20px;margin-left:13px;'}
          = f.text_field :email, class: 'form-control', placeholder: 'Ingrese correo electrónico, Ej: ejemplo@email.com', style: 'width:350px'
          .email-format.hidden.text-danger
            El formato de email es incorrecto, Ej: ejemplo@email.com.

        .form-group.address{style: 'margin-bottom:20px;margin-left:13px;'}
          = f.text_field :address, class: 'form-control', placeholder: 'Ingrese dirección, Ej: Carmen Sylva #3212', style: 'width:350px'
          .address-empty.hidden.text-danger
            Ingrese Dirección, Ej: Carmen Sylva #3212.

        .form-group.phone{style: 'margin-bottom:20px;margin-left:13px;'}
          = f.text_field :phone, class: 'form-control', placeholder: 'Ingrese teléfono de contacto, Ej: 65432762', style: 'width:350px'
          .phone-empty.hidden.text-danger
            Ingrese Teléfono de contacto, Ej: 65432762.
          .phone-length.hidden.text-danger
            Debe tener 8 caracteres, Ej: 65432762.
          .phone-numero.hidden.text-danger
            El teléfono de contacto deben ser numeros.

        .form-group{style: 'margin-bottom:30px;'}
          .option-button.text-center{style: 'margin-left:26px;margin-top:20px;'}
            = f.submit "Ingresar Cliente", class: 'btn btn-lg btn-success', id: "buton-cliente"
            = hidden_field_tag :id, @buy.id
            = link_to 'Cancelar Compra', @buy , method: :delete, data: { confirm: "¿Estás Seguro que deseas esta compra?"}, class: 'btn btn-lg btn-default' 
  

app/views/buys/_form.haml
= form_for @buy do |f|
  = f.fields_for :buy_details do |detail|
    .select_phone.col-md-4.col-md-offset-1
      .form-group
        %h4
          1.- Selecciona marca y modelo teléfonico.
      .form-group
        = select_tag :trademark_id, options_for_select(@trademarks.collect { |trademark| [trademark.name.titleize, trademark.id] }), {  prompt: 'Seleccione una marca', class: 'trademark_select form-control' } 
      
      .form-group
        = detail.select :model_id, options_for_select(@models.collect { |models| [models.name.titleize, models.id] }, 0), { prompt: 'Seleccione un modelo' }, { class: 'model_select form-control' }
  
    .select_state.col-md-4.col-md-offset-1
      .form-group
        %h4
          2.- Selecciona el estado del teléfono.
      .form-group
        = detail.select :state_id, options_for_select(@states.collect { |state| [state.name, state.id] }, 0),{prompt: 'Seleccione el estado del teléfono' }, { class: 'state_select form-control' } 
    
  
  .phone-value.col-md-9.col-md-offset-1
    .form-group
      .phone-total-price
        %h3
          El telefono ha sido cotizado en :
        %h1
          .value

  .options.col-md-4.col-md-offset-4.text-center
    = f.submit "Continuar Compra", class: 'btn btn-lg btn-success buy-bottom'

app/views/buys/_form_add_phone.haml
= form_for @buy do |f|
  = f.fields_for :buy_details, @buy.buy_details.new do |detail|
    .select_phone.col-md-4.col-md-offset-1
      .form-group
        %h4
          1.- Selecciona marca y modelo teléfonico.
      .form-group
        = select_tag :trademark_id, options_for_select(@trademarks.collect { |trademark| [trademark.name.titleize, trademark.id] }), {  prompt: 'Seleccione una marca', class: 'trademark_select form-control' } 
      
      .form-group
        = detail.select :model_id, options_for_select(@models.collect { |models| [models.name.titleize, models.id] }, 0), { prompt: 'Seleccione un modelo' }, { class: 'model_select form-control' }

    .select_state.col-md-4.col-md-offset-1
      .form-group
        %h4
          2.- Selecciona el estado del teléfono.
      .form-group
        = detail.select :state_id, options_for_select(@states.collect { |state| [state.name, state.id] }, 0),{prompt: 'Seleccione el estado del teléfono' }, { class: 'state_select form-control' } 
      
    
    .phone-value.col-md-9.col-md-offset-1
      .form-group
        .phone-total-price
          %h3
            El telefono ha sido cotizado en :
          %h1
            .value

  .options.col-md-4.col-md-offset-4.text-center
    = f.submit "Agregar teléfono", class: 'btn btn-lg btn-success buy-bottom'
    = link_to "Cancelar", @buy ,class: 'btn btn-lg btn-default'
    = hidden_field_tag :buy_id, @buy.id

app/views/buys/add_customer.haml
%h1.text-center
  Ingrese Datos Del Cliente
%hr
%br
=render 'customer_form'

app/views/buys/add_phone.haml
%h1.heading.text-center Cotizar otro teléfono
%hr
%br
  = render 'form_add_phone'

app/views/buys/buy_all.haml
%h1.text-center lista de compras de teléfono 
%hr
%br
  .col-md-10.col-md-offset-1
    %table.table.table-striped
      %thead
        %tr
          %th
            marca
          %th
            modelo
          %th
            estado
          %th
            precio
          %th
            Fecha de emisión
      %tbody
        - @buys.each do |buy|
          - buy.buy_details.each do |detail|
            %tr
              %td
                = detail.model.trademark.name
              %td
                = detail.model.name
              %td
                = detail.state.name
              %td
                = detail.price
              %td
                = detail.buy.created_at.strftime('%d/%m/%Y')
      
    = link_to "Exportar a excel", buy_all_path(format: "xls"), class: 'btn btn-info'
    = paginate @buys

app/views/buys/buy_sucursal.haml
%h1.text-center lista de compras de teléfono por sucursal
%hr
%br
  .col-md-10.col-md-offset-1
    = form_tag buy_sucursal_path, method: :get  do 
      .form-group
        = search_field_tag :q, params[:q], placeholder: 'Ingrese Sucrsal'
        = submit_tag "Buscar"
  .col-md-10.col-md-offset-1
    %table.table.table-striped
      %thead
        %tr
          %th
            marca
          %th
            modelo
          %th
            estado
          %th
            precio
          %th
            Fecha de emisión
      %tbody
        - @buys.each do |buy|
          - buy.buy_details.each do |detail|
            %tr
              %td
                = detail.model.trademark.name
              %td
                = detail.model.name
              %td
                = detail.state.name
              %td
                = detail.price
              %td
                = detail.buy.created_at.strftime('%d/%m/%Y')
    = paginate @buys
    %br
    = link_to "Exportar a excel", buy_sucursal_path(format: "xls", q: params[:q]), class: 'btn btn-info'

app/views/buys/edit.html.erb
<h1>Editing buy</h1>

<%= render 'form' %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

app/views/buys/index.haml
- unless @buys.empty? 
  %h1.text-center Compras realizadas
  %hr
  %br
  .col-md-10.col-md-offset-1
    %table.table.table-striped
      %thead
        %tr
          %th
            Sucursal
          %th
            Cliente
          %th
            Fecha de emisión
          %th
      %tbody
        - @buys.each do |buy|
          %tr
            %td
              = buy.member.user.username.capitalize unless buy.member.nil?
            %td
              = buy.customer.full_name unless buy.customer.nil?
            %td
              = buy.created_at.strftime('%d/%m/%Y')
            %td
              = link_to ' Ver Detalle de Compra', buy, class: 'btn btn-default fa fa-eye'
- else
  .empty.text-center
    %h1
      No hay compras realizadas.
      %br
      %br
      %br
      = link_to ' Volver a inicio', root_path, class: 'btn btn-lg btn-default'
          

app/views/buys/new.haml
%h1.heading.text-center Cotizar teléfono
%hr
%br
  = render 'form'

app/views/buys/show.haml
%h1.heading.text-center Detalles de compra
%hr
%br
.row
  .col-md-2
  .buy-heading-client.col-md-4
    .heading-title
      %h4
        Datos Sucursal
      %hr
    .title-client.pull-left
      Sucursal  :
      %br
      Dirección:
      %br
      Fecha compra :
    .value-client.pull-right
      = @buy.member.sucursal.name unless @buy.member.nil?
      %br
      = @buy.member.sucursal.address unless @buy.member.nil?
      %br
      = @buy.created_at.strftime("%d/%m/%Y")
  .buy-heading-custumer.col-md-4.col-md-offset-1
    .heading-customer
      %h4
        Datos Cliente
      %hr
    .title-customer.pull-left
      Rut :
      %br
      Nombre :
      %br
      Dirección :
      %br
      Teléfono de contacto :
      %br
    .value-customer.pull-right
      - unless @buy.customer.nil?
        = @buy.customer.rut 
        %br
        = @buy.customer.full_name
        %br
        = @buy.customer.address    
        %br
        = @buy.customer.phone   

.row
  .col-md-2
  .total-value.col-md-9
    .title-total-value.text-center
      %h3
        Valor a pagar
    .value-total.text-center
      %h1
        = number_to_currency(@buy.get_total_price)

.row{ style: 'margin-top:10px;'}
  .col-md-3
  .option-button.col-md-8
    - if @buy.coupon.nil?    
      = link_to 'Agregar otro teléfono', add_phone_buy_path, class: 'btn btn-lg btn-success'
      = link_to 'Generar cupón de descuento y finalizar compra', {controller: "coupons", :buy_id => @buy}, method: :create, class: 'btn btn-lg btn-primary'
      = link_to 'Cancelar Compra', @buy , method: :delete, data: { confirm: "¿Estás Seguro que deseas esta compra?"}, class: 'btn btn-lg btn-default' 
    - else
      = link_to '#show-coupon', class: 'btn btn-lg btn-primary', data: { toggle: 'modal', target: '#show-coupon' } do
        %span Ver e imprimir cupón
      = link_to 'Terminar Compra', root_path,class: 'btn btn-lg btn-success'
      

.row
  .col-md-3
  .buy-details-table.col-md-6
    %table.table.table-striped
      %thead
        %tr
          %th
            Marca
          %th
            Modelo
          %th
            Estado Teléfono
          %th
            Precio a pagar
          %th
          %th

      %tbody
        - @buy.buy_details.each do |detail|
          %tr
            %td
              %strong
                = detail.model.trademark.name
            %td
              %strong
                = detail.model.name
            %td
              %strong
                = detail.state.name
            %td
              %strong

                = number_to_currency(detail.price)  
            %td
              - if @buy.coupon.nil?
                = link_to " Quitar Telefono", detail , method: :delete, data: { confirm: "¿Estás Seguro que deseas eliminar  el teléfono #{ detail.model.trademark.name} #{detail.model.name} de esta compra?"}, class: 'btn btn-danger fa fa-close'



= render 'buy_modals'